GET https://localhost:7067/api/Auth HTTP/1.1
Authorization: Bearer  eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzdHJpbmciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwiZXhwIjoxNjgwNTQ3NzU2fQ.kaWPABpOi0uBn4HgqE0EFtAOs70bPQzVjViYAJdXruPYQqFBTD6ZQgAfS39gBe9VPhTuC6RDkxxtxDk8JG_4fQ
